import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import { getDatabase } from "../src/utils/database";
import { Card } from "react-bootstrap";
import Link from "next/link";
import { v4 as uuidv4 } from "uuid";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await getDatabase();
  const games = await data
    .db("NextJSGameCatalogue")
    .collection("games")
    .find()
    .toArray();
  const gamesStringinfy = JSON.stringify(games);
  const gamesParse = JSON.parse(gamesStringinfy);
  const gamesOfTheMoment = gamesParse.slice(0, 5);
  const bestSellers = gamesParse.slice(15, 26);
  const id = uuidv4();
  console.log("id :", id);

  return {
    props: {
      games: gamesParse,
      gamesOfTheMoment: gamesOfTheMoment,
      bestSellers: bestSellers,
      id: id,
    },
  };
};
type GamesProps = {
  games: any;
  gamesOfTheMoment: any;
  bestSellers: any;
  id: string;
};

const Home: React.FC<GamesProps> = ({
  games,
  gamesOfTheMoment,
  bestSellers,
  id,
}) => {
  return (
    <div className={styles.container} key={id}>
      <Head>
        <title>Game CAtalogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to Next Game Catalogue!</h1>
          <div className={styles.background}></div>
          <div> Jeux du moments</div>
          <div className="row">
            {gamesOfTheMoment.map((game: any) => {
              return (
                <>
                  <Link href={`/games/${game.slug}`}>
                    <a className={styles.card}>
                      <Card style={{ width: "12rem" }}>
                        <Card.Img
                          style={{ width: "12rem", height: "12rem" }}
                          src={game.cover.url}
                        />
                      </Card>
                      <Card.Title className="text-center">
                        {game.name} &rarr;
                      </Card.Title>
                      <Card.Text className="text-center text-secondary">
                        {game.price} €
                      </Card.Text>
                    </a>
                  </Link>
                </>
              );
            })}
          </div>
          <div> Meilleures ventes </div>
          <div className="row">
            {bestSellers.map((game: any) => {
              return (
                <>
                  <Link href={`/games/${game.slug}`}>
                    <a className={styles.card}>
                      <Card style={{ width: "12rem" }}>
                        <Card.Img
                          style={{ width: "12rem", height: "12rem" }}
                          src={game.cover.url}
                        />
                      </Card>
                      <Card.Title className="text-center">
                        {game.name} &rarr;
                      </Card.Title>
                      <Card.Text className="text-center text-secondary">
                        {game.price} €
                      </Card.Text>
                    </a>
                  </Link>
                </>
              );
            })}
          </div>
        </main>
      </Layout>
    </div>
  );
};

export default Home;
